services:
  django:
    container_name: simple_lms
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
  postgres:
    container_name: simple_db
    image: postgres:17.0
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5501:5432"